README.md
=> Update README with model size ranges

README.md
Refinement of model download instructions in the iOS app README.
- Updated the URL for downloading YOLOv8 CoreML INT8 models to point directly to the releases page.
- Purpose: To make the process of acquiring pre-trained models for the YOLO iOS app more straightforward.
- Impact: Users will have a clearer guide and direct access to the necessary model files, potentially reducing confusion and streamlining the app setup process. 📲🛠️
=> Update releases URL in README

README.md
Improvement of App Store link in the README for enhanced user navigation.
- Updated the app store link in the README.md.
- Ensured that the link directs users to the correct app page.
- **Purpose:** To correct a previously incorrect or outdated link that pointed to Xcode instead of the Ultralytics YOLO iOS App, making it easier for users to find and download the app.
- **Impact:** Enhances user experience by providing a direct and accurate link, helping to increase visibility and accessibility of the Ultralytics YOLO iOS App for potential users.
=> Fix app store URL

README.md
Enhanced code clarity for model loading and export in YOLO iOS App documentation.
- Refactored model loading and exporting code into separate steps.
- Improved readability by assigning the loaded model to a variable before exporting.
- **Purpose:** To make the documentation easier to understand, especially for new users or developers.
- **Impact:** Enhances the clarity of the README, potentially reducing setup errors and improving user onboarding experience. 📈👨‍💻👩‍💻
=> Update README.md code example

.github/workflows/format.yml, README.md, YOLO/AppDelegate.swift, YOLO/Utilities/BoundingBoxView.swift, YOLO/Utilities/ThresholdProvider.swift, YOLO/VideoCapture.swift, YOLO/ViewController.swift
This PR should now run swift formatting that was added in #54.
=> Run new Swift formatting

.github/workflows/cla.yml, .github/workflows/format.yml, README.md, YOLO/Models/README.md
This [Ultralytics](https://ultralytics.com) PR refactors code to improve performance and readability. 🔄
- 🚀 Optimized various functions for faster execution.
- 🧩 Simplified complex logic for better understanding and maintenance.
- 🗑️ Removed redundant code to streamline operations.
- 📚 Improved code structure and organization.
These changes aim to enhance the overall quality and efficiency of the code. 🌟
- [About Us](https://www.ultralytics.com/about) 🌐
- [Install the Ultralytics App](https://www.ultralytics.com/app-install) 📲
- [Read Our Blog](https://www.ultralytics.com/blog) 📝
- [Learn about YOLO](https://www.ultralytics.com/yolo) 🤖
- [Explore Ultralytics HUB](https://www.ultralytics.com/hub) 🚀
- [Check Out Our Plans](https://www.ultralytics.com/plans) 💼
- [Join our …
=> Ultralytics Code Refactor https://ultralytics.com/actions

.github/workflows/cla.yml, .github/workflows/format.yml, .github/workflows/tag.yml
This PR updates all YAML file headers to use a standardized license format. 🔄
- 📝 Standardized header: `# Ultralytics 🚀 AGPL-3.0 License - https://ultralytics.com/license`
- 🧹 Ensures consistent spacing after headers
- 🔍 Applies to all YAML files except those in `venv`
Learn more about [Ultralytics licensing](https://ultralytics.com/license) 📚
Minor updates to GitHub workflows to improve clarity and formatting.
- Updated license comment formatting in multiple workflow files to include a clearer structure and link to Ultralytics' license page.
- No functional changes to the workflows themselves.
- 📘 **Improved Clarity**: The updated formatting provides a more professional and standardized look, …
=> Standardize license headers in TOML/YAML files

ExampleApps/README.md, ExampleApps/YOLORealTimeSwiftUI/YOLORealTimeSwiftUITests/README.md, ExampleApps/YOLORealTimeUIKit/YOLORealTimeUIKitTests/README.md, ExampleApps/YOLOSingleImageSwiftUI/YOLOSingleImageSwiftUITests/README.md, ExampleApps/YOLOSingleImageUIKit/YOLOSingleImageUIKitTests/README.md, Package.swift, README.md, Sources/YOLO/README.md, Tests/YOLOTests/README.md, Tests/YOLOTests/Resources/README.md, Tests/YOLOTests/YOLOTests.swift, YOLOiOSApp/README.md
This [Ultralytics](https://www.ultralytics.com/) PR refactors code to improve performance and readability. 🔄
- 🚀 Optimized various functions for faster execution.
- 🧩 Simplified complex logic for better understanding and maintenance.
- 🗑️ Removed redundant code to streamline operations.
- 📚 Improved code structure and organization.
These changes aim to enhance the overall quality and efficiency of the code. 🌟
- [About Us](https://www.ultralytics.com/about) 🌐
- [Install the Ultralytics App](https://www.ultralytics.com/app-install) 📲
- [Read Our Blog](https://www.ultralytics.com/blog) 📝
- [Learn about YOLO](https://www.ultralytics.com/yolo) 🤖
- [Explore Ultralytics HUB](https://www.ultralytics.com/hub) 🚀
- [Check Out Our Plans](https://www.ultralytics.com/plans) 💼
- [Join our …
=> Ultralytics Refactor https://ultralytics.com/actions

.github/workflows/ci.yml, Sources/YOLO/YOLOView.swift
Improved the iOS app's continuous integration workflow for more reliable testing and accurate code coverage reporting. 🚀
- Added a step to display the Xcode version used in CI for better transparency.
- Simplified and generalized the process for selecting an available iOS simulator, making it less dependent on specific device models.
- Enhanced the build and test steps to ensure code coverage is always enabled and results are consistently generated.
- Switched to generating code coverage reports in the lcov format, which is widely supported.
- Updated the Codecov upload step to use the new lcov report, ensuring more accurate coverage data is sent.
- 🛠️ Makes the CI process more robust and less likely …
=> Fix tests by removing preconcurrency

.github/workflows/ci.yml
Improves the code coverage report generation in the iOS app's CI workflow, making it more robust and reliable. 🚀
- Enhanced logic for finding the correct binary and coverage data files needed to generate code coverage reports.
- Added detailed checks and fallback options to handle different project structures (both app and test bundles).
- Improved error handling and messaging, ensuring the workflow doesn't fail if coverage files are missing.
- Ensures an empty coverage report is created if necessary, preventing CI failures in downstream steps.
- Increases reliability of automated code coverage reporting, reducing false negatives and workflow interruptions.
- Makes it easier to diagnose issues with …
=> Fix attempt for coverage report

.github/workflows/ci.yml, Tests/YOLOTests/Resources/README.md, Tests/YOLOTests/Resources/download-test-models.sh
Added a `download-test-models.sh` script to automate the download and preparation of YOLO model files for testing. Updated `README.md` in `Tests/YOLOTests/Resources` with directory structure and guidelines for proper model packaging. Removed `.gitkeep` as it's no longer necessary.
This update streamlines how YOLO model files are downloaded for testing in the iOS app, making the process more organized and user-friendly. 🚀
- Introduced a new `download-test-models.sh` script to automate downloading and preparing YOLO model files for tests.
- Updated the continuous integration (CI) workflow to use this script instead of inline commands.
- Improved documentation in the test resources README, including a …
=> Add model download script and update test resource docs

ExampleApps/README.md, Tests/YOLOTests/README.md, YOLOiOSApp/YOLOiOSApp.xcodeproj/project.pbxproj, YOLOiOSApp/YOLOiOSApp/ViewController.swift
Streamlined and automated the process for exporting and zipping multiple YOLO11 model types to CoreML format for iOS app integration. 🚀
- Introduced a new Python function to export all YOLO11 model types (detection, segmentation, classification, pose, OBB) and sizes in one go.
- Automatically zips each exported CoreML model package for easier handling.
- Simplified and consolidated the example code in the README for better usability.
- **Saves Time:** Users can now export and prepare all required YOLO11 models for iOS with a single command, reducing manual steps.
- **Improved Usability:** The new approach makes it easier for developers to integrate multiple model types into their iOS projects.
- …
=> Update export Python script in READMEs

ExampleApps/README.md, Tests/YOLOTests/README.md, YOLOiOSApp/README.md
This update streamlines and improves the process for exporting YOLO11 models to CoreML for iOS, making it easier to handle multiple model types and sizes with a single script. 🚀
- Introduced a unified Python function (`export_and_zip_yolo_models`) to export and zip YOLO11 models for all tasks (detection, segmentation, classification, pose, OBB) and sizes.
- Automatically sets recommended input image sizes and NMS (Non-Maximum Suppression) settings based on the model type.
- Updated documentation across example apps and test directories to reflect the new, simplified export process.
- **Simplifies Workflow:** Users can now export all required YOLO11 models for iOS with one script, reducing manual steps …
=> Fix Classify export `imgsz`

ExampleApps/YOLORealTimeSwiftUI/YOLORealTimeSwiftUITests/README.md, Sources/YOLO/README.md, Tests/YOLOTests/README.md, YOLOiOSApp/README.md
Minor documentation updates improve clarity, fix links, and ensure accurate references across the YOLO iOS app project. 📝✨
- Fixed and updated several hyperlinks in README files for better accuracy and reliability.
- Corrected references to Apple and Ultralytics documentation, including Swift Concurrency and resource bundling.
- Updated license links to point to the correct OSI-approved AGPL-3.0 pages.
- Clarified iOS version requirements and fixed related URLs.
- Ensures users and developers can easily access the correct resources and documentation. 🔗
- Reduces confusion by providing accurate information about requirements and licensing. 📚
- Improves the overall professionalism and usability of the …
=> Redirect links

ExampleApps/README.md, YOLOiOSApp/YOLOiOSApp.xcodeproj/project.pbxproj, YOLOiOSApp/YOLOiOSApp.xcodeproj/xcshareddata/xcschemes/YOLOiOSApp.xcscheme, YOLOiOSApp/YOLOiOSApp/Info.plist, YOLOiOSApp/YOLOiOSApp/ModelDownloadManager.swift, YOLOiOSApp/YOLOiOSApp/ViewController.swift
This update improves the YOLO iOS app's build process, asset handling, and minor code quality, making development smoother and the app more robust. 🚀📱
- Enabled parallel building of independent targets in Xcode for faster builds.
- Updated Xcode project and scheme settings to the latest version for better compatibility.
- Improved asset catalog handling by generating Swift asset symbol extensions.
- Incremented the app's build version from 396 to 397.
- Minor code cleanup in the model download and view controller files.
- **Faster Development:** Parallel builds speed up the development process for contributors.
- **Better Asset Management:** Enhanced asset handling makes it easier for developers to …
=> Fix warnings

ExampleApps/README.md, README.md, YOLOiOSApp/README.md
This update refreshes the app preview images in the documentation and improves the visual presentation of the Ultralytics YOLO iOS App on GitHub. 🖼️✨
- Updated the main preview image in both the root and app-specific README files to a new, higher-quality version.
- Adjusted image formatting for better display (increased width to 100% and added spacing).
- Minor cleanup in the example app documentation for clarity.
- Provides a clearer, more attractive visual overview of the Ultralytics YOLO iOS App for users and developers.
- Enhances first impressions and usability for those browsing the repository or considering using the app.
- No changes to app functionality—documentation only, so no risk to …
=> Update README App Store Previews

ExampleApps/YOLORealTimeUIKit/YOLORealTimeUIKit.xcodeproj/project.pbxproj, ExampleApps/YOLOSingleImageSwiftUI/YOLOSingleImageSwiftUI.xcodeproj/project.pbxproj, YOLOiOSApp/YOLOiOSApp.xcodeproj/project.pbxproj, YOLOiOSApp/YOLOiOSApp/Info.plist, YOLOiOSApp/YOLOiOSApp/Main.storyboard
This update improves how the YOLO iOS app and its example projects reference local Swift packages, bumps the app version, and makes a minor UI adjustment. 🚀
- Updated local Swift package reference paths in project files for both the main app and the UIKit example.
- Increased the app's build version from 408 to 409.
- Slightly adjusted the position of the version label in the app's main storyboard.
- 📦 **Simplifies development:** The new package paths make it easier for developers to manage and build the app locally, reducing confusion and potential errors.
- 🆙 **Version tracking:** The version bump helps track changes and ensures users and developers know they're using the latest build.
- 🎨 **UI …
=> Fix Xcode Cloud build directory issues

.github/workflows/publish.yml
Adds a new GitHub Actions workflow to automate publishing the YOLO iOS app to TestFlight and prepare for App Store submission. 🚀📱
- Introduces a `publish.yml` workflow for the YOLO iOS app.
- Enables manual (on-demand) publishing to TestFlight and/or preparing for App Store submission.
- Automates merging code into the `testflight` branch for TestFlight deployments.
- Sets up a placeholder for App Store submission steps (to be implemented later).
- Restricts App Store submission to specific trusted users.
- Simplifies and streamlines the release process for the YOLO iOS app.
- Reduces manual work and potential errors during deployment.
- Allows faster and more reliable testing via TestFlight for users …
=> Download models for app as well as tests

.github/workflows/publish.yml
Minor update to Slack notifications for iOS app releases.
- Updated Slack notification message to remove the version number from "YOLO11 iOS" to just "YOLO iOS" in release alerts.
- Ensures release notifications are more general and not tied to a specific YOLO version.
- Reduces confusion and keeps messaging consistent as new versions are released.
- No impact on app functionality—this is a communication improvement only. 🚀
=> Cleanup publish.yml

.github/workflows/ci.yml
Updated the iOS app's continuous integration workflow to use the latest macOS environment. 🚀
- Changed the GitHub Actions workflow to run tests on macOS-latest instead of macOS-15.
- Ensures the app is tested on the most up-to-date macOS version, improving compatibility and reliability.
- Reduces risk of issues caused by outdated environments, leading to smoother development and deployment for users.
=> Update ci.yml to macos-latest

.github/workflows/publish.yml
Improves the workflow for publishing the YOLO iOS app to TestFlight by streamlining branch creation and commit history management. 🚀
- Simplifies the process of creating the `testflight` branch directly from the source branch (defaulting to `main`).
- Squashes all previous commits into a single commit for a cleaner history.
- Ensures dependency resolution and includes updated package files in the commit.
- Updates the commit message to clearly show the app version and build number.
- **Cleaner Branch History:** Makes the `testflight` branch easier to review and manage by consolidating all changes into one commit.
- **Streamlined Publishing:** Reduces manual steps and potential errors during the …
=> Simplify publish.yml

.github/workflows/format.yml, Sources/YOLO/BasePredictor.swift, Sources/YOLO/Plot.swift, Sources/YOLO/Segmenter.swift, Sources/YOLO/VideoCapture.swift, Sources/YOLO/YOLOView.swift, Tests/YOLOTests/BasePredictorTests.swift, Tests/YOLOTests/PlotTests.swift, Tests/YOLOTests/ThresholdProviderTests.swift, Tests/YOLOTests/YOLOIntegrationTests.swift, Tests/YOLOTests/YOLOMainTests.swift, Tests/YOLOTests/YOLOResultTests.swift, Tests/YOLOTests/YOLOTaskTests.swift, YOLOiOSApp/YOLOiOSApp/ModelDownloadManager.swift, YOLOiOSApp/YOLOiOSApp/ViewController.swift
@asabri97 @john-rocky re-enabled Swift formatting here. I don't know why it was disabled but it should never be disabled in this repo.
Improved code formatting workflow to support Swift files and run on macOS for better compatibility with iOS development. 🚀
- Workflow now runs on macOS instead of Ubuntu.
- Added automatic Swift code formatting.
- Formatting and checks still include Python, YAML, JSON, Markdown, CSS, and spelling.
- Workflow triggers updated to apply to all branches, not just main.
- Ensures Swift code (used in iOS apps) is automatically formatted, leading to cleaner and more consistent code.  
- Running on macOS is essential for Swift and iOS development, improving compatibility and …
=> Update format.yml for Swift formatting
